src/Entity/Produits.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitsRepository")
 */
class Produits
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="float")
     */
    private $poids;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $informations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProduitImage", mappedBy="produit")
     */
    private $produitImages;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ventes", mappedBy="produit")
     */
    private $ventes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function __construct()
    {
        $this->produitImages = new ArrayCollection();
        $this->ventes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPoids(): ?float
    {
        return $this->poids;
    }

    public function setPoids(float $poids): self
    {
        $this->poids = $poids;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getInformations(): ?string
    {
        return $this->informations;
    }

    public function setInformations(?string $informations): self
    {
        $this->informations = $informations;

        return $this;
    }

    public function getCategories(): ?categorie
    {
        return $this->categories;
    }

    public function setCategories(?categorie $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    /**
     * @return Collection|ProduitImage[]
     */
    public function getProduitImages(): Collection
    {
        return $this->produitImages;
    }

    public function addProduitImage(ProduitImage $produitImage): self
    {
        if (!$this->produitImages->contains($produitImage)) {
            $this->produitImages[] = $produitImage;
            $produitImage->setProduit($this);
        }

        return $this;
    }

    public function removeProduitImage(ProduitImage $produitImage): self
    {
        if ($this->produitImages->contains($produitImage)) {
            $this->produitImages->removeElement($produitImage);
            // set the owning side to null (unless already changed)
            if ($produitImage->getProduit() === $this) {
                $produitImage->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Ventes[]
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Ventes $vente): self
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes[] = $vente;
            $vente->setProduit($this);
        }

        return $this;
    }

    public function removeVente(Ventes $vente): self
    {
        if ($this->ventes->contains($vente)) {
            $this->ventes->removeElement($vente);
            // set the owning side to null (unless already changed)
            if ($vente->getProduit() === $this) {
                $vente->setProduit(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Entity
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length( min=6,  minMessage="Votre Mote de passe doit faire au moins 8 caractères")
     */
    private $PasswordUser;

    /**
     * @Assert\EqualTo(propertyPath="PasswordUser", message="Vous n'avez pas confirmé votre mot de passe")
     */
    public $PasswordConfirmer;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email
     * @Assert\Email(
     *     message = " Email '{{ value }}' n'est pas  valide .")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File(
     *     mimeTypes = {"image/jpeg","image/gif","image/png"},
     *     mimeTypesMessage = "Please upload a valid Image"
     * )
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Posts", mappedBy="author")
     */
    private $posts;
  
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="author", orphanRemoval=true)
     */
    private $comment;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Roles", mappedBy="users")
     */
    private $UserRoles;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couverture;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Safran", mappedBy="author")
     */
    private $safrans;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vedio", mappedBy="author")
     */
    private $vedio;

    
    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        if(empty($this->slug)){ $this->slug = "non indique" ; }
        if(empty($this->content)){ $this->content = "non prisez" ; }
        if(empty($this->couverture)){ $this->couverture = "couvert.jpg" ; }
    }
        
    public function getFullname()
    {
        return "{$this->firstname } {$this->lastname}";
    }

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->comment = new ArrayCollection();
        $this->UserRoles = new ArrayCollection();
        $this->amisone = new ArrayCollection();
        $this->amistwo = new ArrayCollection();
        $this->safrans = new ArrayCollection();
        $this->vedio = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar()
    {
        return $this->avatar;
    }

    public function setAvatar( $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|Posts[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Posts $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setAuthor($this);
        }

        return $this;
    }

    public function removePost(Posts $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getAuthor() === $this) {
                $post->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }



    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPasswordUser(): ?string
    {
        return $this->PasswordUser;
    }

    public function setPasswordUser(string $PasswordUser): self
    {
        $this->PasswordUser = $PasswordUser;

        return $this;
    }

    public function getPassword(){
        return $this->PasswordUser;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getRoles()
    {
        $roles = $this->UserRoles->map(function($role){
            return $role->getLibelle();
        })->toArray();

        $roles [] = 'ROLE_USER';
        return $roles;
    }

    public function getSalt()
    { 

    }

    public function eraseCredentials()
    {

     }

    /**
     * @return Collection|Roles[]
     */
    public function getUserRoles(): Collection
    {
        return $this->UserRoles;
    }

    public function addUserRole(Roles $userRole): self
    {
        if (!$this->UserRoles->contains($userRole)) {
            $this->UserRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Roles $userRole): self
    {
        if ($this->UserRoles->contains($userRole)) {
            $this->UserRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    public function getCouverture(): ?string
    {
        return $this->couverture;
    }

    public function setCouverture(?string $couverture): self
    {
        $this->couverture = $couverture;

        return $this;
    }

    

   
    /**
     * @return Collection|Safran[]
     */
    public function getSafrans(): Collection
    {
        return $this->safrans;
    }

    public function addSafran(Safran $safran): self
    {
        if (!$this->safrans->contains($safran)) {
            $this->safrans[] = $safran;
            $safran->setAuthor($this);
        }

        return $this;
    }

    public function removeSafran(Safran $safran): self
    {
        if ($this->safrans->contains($safran)) {
            $this->safrans->removeElement($safran);
            // set the owning side to null (unless already changed)
            if ($safran->getAuthor() === $this) {
                $safran->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Vedio[]
     */
    public function getVedio(): Collection
    {
        return $this->vedio;
    }

    public function addVedio(Vedio $vedio): self
    {
        if (!$this->vedio->contains($vedio)) {
            $this->vedio[] = $vedio;
            $vedio->setAuthor($this);
        }

        return $this;
    }

    public function removeVedio(Vedio $datepub): self
    {
        if ($this->vedio->contains($vedio)) {
            $this->vedio->removeElement($vedio);
            // set the owning side to null (unless already changed)
            if ($vedio->getAuthor() === $this) {
                $vedio->setAuthor(null);
            }
        }

        return $this;
    }


     
}

src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Produits;
use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ProduitsType extends AbstractType
{
    private function getConfig($label,$place )
    {
        return  [
            'label' => $label,
            'attr' => [
                'placeholder' => $place
            ]
        ];
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reference',TextType::class,$this->getConfig('Référebce  :','Tapez Référence de produit'))
            ->add('slug',TextType::class,$this->getConfig('Désignation  :','Tapez Désignation de produit'))
            ->add('content',TextareaType::class, $this->getConfig('Introduction :', 'Tapez super Introduction pour votre produit'))
            ->add('poids',NumberType::class, $this->getConfig('Quantité :', 'Tapez la Quantité'))
            ->add('prix',NumberType::class, $this->getConfig('Prix Unitaire :', 'Tapez le Prix de produit'))
            ->add('description',TextareaType::class, $this->getConfig('description :', 'Tapez super description pour votre produit'))
            ->add('informations',TextareaType::class, $this->getConfig('informations complementaire :', 'Tapez super informations pour votre produit'))
            ->add('image', FileType::class,array('data_class' => null),$this->getConfig("Url de l'image principale :", "Donne l'adresse de l'image qui donne vraiment envie"))
            ->add('categories',EntityType::class, [
                'class' => Categorie::class,
                'choice_label' => 'designation',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
        ]);
    }
}

templates/produits/pages/cart.html.twig
    {% extends 'base.html.twig' %}

{% block title %}carte des produit
{% endblock %}

{% block body %}

{% include "produits/partials/navbar.html.twig"  %}
    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>Désignation</th>
						        <th>Prix</th>
						        <th>Quantité</th>
						        <th>Total</th> 
								<th>&nbsp;</th>
						      </tr>
						    </thead>
						    <tbody>
								{% set total = 0 %}	
								{% if produits | length > 0 %}
								{% for produi in produits %}
								{% if produi.produit  is empty  %}
								{% else %}
						      <tr class="text-center">
									<td class="image-prod"><img class="img" src=" {{ asset("/produits/produit/"~ produi.produit.image ) }}"></td>
									<td class="product-name">
										<h3>{{ produi.produit.slug }}</h3>
										<p>{{ produi.produit.content|slice(0,50)|raw }}</p>
									</td>
									<td class="price"> {{ produi.produit.prix|number_format(2, '.', ',') }} $</td>
									<td class="quantity">
										<div class="input-group mb-3">
											<input type="text" name="quantity" class="quantity form-control input-number" value="{{ produi.quantite  }}" min="1" max="100">
										</div>
									</td>
									{% set var = produi.quantite * produi.produit.prix  %}
									<td class="total"> {{ var|number_format(2, '.', ',') }} $</td>
									<td class="product-remove"><a href="{{ path('cart_remove',{ 'id': produi.produit.id }) }}"><span class="ion-ios-close"></span></a></td>
						      </tr><!-- END TR-->
								{% set total = total + var %}
								{% endif %}
								{% endfor %}
								{% else %}
									<tr>
										<td>Surprise, le panier est vide !!</td>
									</tr>
								{% endif %}
						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-end">
    			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
    					<h3>Sous TOTAL</h3>
    					<p class="d-flex">
    						<span>Sous Total</span>
    						<span>{{ total|number_format(2, '.', ',') }} $</span>
    					</p>
    					<p class="d-flex">
    						<span>TVA</span>
    						<span>0.00 $</span>
    					</p>
    					<hr>
    					<p class="d-flex total-price">
    						<span>Total</span>
    						<span>{{ total|number_format(2, '.', ',') }} $</span>
    					</p>
    				</div>
    				<p><a href="{{ path('chekout_page',{'montant' : total }) }}" class="btn btn-primary py-3 px-4">Passer à la caisse</a></p>
    			</div>
    		</div>
			</div>
		</section>

	<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Abonnez-vous à notre EPICERIE EN LIGNE </h2>
          	<span>Recevez des mises à jour par e-mail sur nos dernières boutiques et offres spéciales</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}

templates/produits/pages/chekout.html.twig
    {% extends 'base.html.twig' %}

{% block title %}carte des produit
{% endblock %}

{% block body %}

{% include "produits/partials/navbar.html.twig"  %}
 <div class="">
    <section class="mt-4">{{ form_start(form) }}
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-7 ftco-animate">
			
						<h3 class="mb-4 billing-heading">Détails de facturation</h3>
						<div class="row align-items-end">
							<div class="col-md-12">
								<div class="form-group">
									{{ form_row(form.nomComplet) }}
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{{ form_row(form.adresse) }}
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
								{{ form_row(form.maison) }}
							</div>
							</div>
							<div class="w-100"></div>
								<div class="col-md-12">
								<div class="form-group">
									<label for="country">État / Pays</label>
									<div class="select-wrap">
								<select required name="pays" id="" class="form-control">
								<option selected></option>
								<option value="Morocco" selected>Moroc</option>
								<option value="France">France</option>
									{% include "produits/partials/country.html.twig" %}
								</select>
								</div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{{ form_row(form.postal) }}
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									{{ form_row(form.tele) }}
								</div>
							</div>
							<div class="col-md-12">
								<div class="form-group">
									{{ form_row(form.email) }}
								</div>
							</div>
						<div class="col-md-12">
							<div class="form-group">
								{{ form_row(form.password) }}
							</div>
						</div>
						<div class="w-100"></div>
					</div>
					<hr>

					<div class="form-group">
						<div class="col-md-12">
							<div class="checkbox">
							<p>Vos données personnelles seront utilisées pour le traitement de votre commande, vous accompagner au cours de votre visite du site web, et pour d’autres raisons décrites dans notre politique de confidentialité.</p>
								<label><input required type="checkbox" name="valider" value="true" class="mr-2">  J’ai lu et j’accepte les conditions générales *</label>
							</div>
						</div>
					</div>
					
					<p><button type="submit" class="btn btn-primary py-3 px-4">Commander</button></p>
					</div>
					<div class="col-xl-5">
	          <div class="row mt-5 pt-3">
	          	<div class="col-md-12 d-flex mb-5">
	          		<div class="cart-detail cart-total p-3 p-md-4">
	          			<h3 class="billing-heading mb-4">Sous Total</h3>
	          			<p class="d-flex">
		    						<span>Sous total</span>
		    						<span>{{ montant|number_format(2, '.', ',') }} $</span>
		    					</p>
		    					<p class="d-flex">
		    						<span>TVA </span>
		    						<span>0.00 $</span>
		    					</p>
		    					</p>
		    					<hr>
		    					<p class="d-flex total-price">
		    						<span>Montant TOTAL</span>
		    						<span>{{ montant|number_format(2, '.', ',') }} $</span>
		    					</p>
								</div>
	          	</div>
	          	<div class="col-md-12">
	          		<div class="cart-detail p-3 p-md-4">
						  <h3 class="billing-heading mb-4">Mode de paiement</h3>
						  			<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" value="à Livraison" required class="mr-2"> à Livraison </label>
											</div>
										</div>
									</div>
						  			<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" value="Wafacache Expresse" required class="mr-2"> Wafacache Expresse </label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio"  name="optradio" value="Virement bancaire" required class="mr-2"> Virement bancaire </label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" value="Paiements par chèque" required class="mr-2"> Paiements par chèque</label>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<div class="radio">
											   <label><input type="radio" name="optradio" value="Paypal" required class="mr-2"> Paypal<img class="img " src="{{ asset('/produits/logo_paypal_moyens_paiement_fr.jpg') }}"></label>
											</div>
										</div>
									</div>
									
								</div>
	          	</div> 
	          </div>
          </div> <!-- .col-md-8 -->
        </div>
      </div>
	 
	  {{ form_end(form) }}
    </section> <!-- .section -->

	<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Abonnez-vous à notre EPICERIE EN LIGNE </h2>
          	<span>Recevez des mises à jour par e-mail sur nos dernières boutiques et offres spéciales</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}

templates/produits/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Présentation
{% endblock %}

{% block body %}

{% include "produits/partials/navbar.html.twig"  %}

<div class="hero-wrap hero-bread" style="background-image: url( {{ asset('/images/contact.jpg') }} );">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Page</a></span> <span>Contactez Nous</span></p>
            <h1 class="mb-0 bread">Contact us</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section contact-section bg-light">
      <div class="container">
      	<div class="row d-flex mb-5 contact-info">
          <div class="w-100"></div>
          <div class="col-md-3 d-flex mt-2">
          	<div class="info bg-white p-4">
	            <p><span>Addresse:</span> N° 122 Hay Tamassinte Ouarzazate Maroc</p>
	          </div>
          </div>
         
          <div class="col-md-3 d-flex mt-2">
          	<div class="info bg-white p-4">
	            <p><span classd-flex>Email:</span> <a href="mailto:brahimbouhaddou12@gmail.com">brahimbouhaddou12@gmail.com</a></p>
            </div>
          </div>
            <div class="col-md-3 d-flex mt-2">
            <div class="info bg-white p-4">
	            <p><span>phone:</span> <a href="">+ 212 666 34 00 50</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex mt-2">
          	<div class="info bg-white p-4">
	            <p><span>Site Web</span> <a href="#">www.ighri.com</a></p>
	          </div>
          </div>
        </div> 
        <div class="row block-9">
          <div class="col-md-6 ">
          	<div  class="bg-white  h-100">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2927.691655257743!2d-6.9717356853841554!3d30.933500582980898!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzDCsDU2JzAwLjYiTiA2wrA1OCcxMC40Ilc!5e1!3m2!1sfr!2sma!4v1576431941916!5m2!1sfr!2sma" height="590" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
             </div>
          </div>
          <div class="col-md-6  mt-2">
            {{form_start(form) }}
            {{form_widget(form) }}
            <div class="text-center">
            <input type="submit" value="Envoyer Message" class="btn btn-primary py-3 px-5 text-center">
            </div>
            {{form_end(form) }}
          </div> 
          </div>
      </div>
    </section>
    {% endblock %}

templates/produits/pages/produitParCategorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vente produits
{% endblock %}

{% block body %}

{% include "produits/partials/navbar.html.twig"  %}

 <div class="hero-wrap hero-bread" style="background-image: url( {{ asset('/produits/safran23.jpg') }});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Bio</a></span> <span>100 %</span></p>
            <h1 class="mb-0 bread">SAFRAN TALIOUINE</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg pt-4 pb-4">
      <div class="container">
        <div class="row">
       
     <div class="col-lg-9 ftco-animate ">
        {% include "produits/partials/produitType.html.twig" %}
          
	</div> <!-- .col-md-9 -->
   <div class="col-lg-3 sidebar ftco-animate">
           {% include "produits/partials/slide.html.twig" %}
          </div>
</div>
</div>
</section> <!-- .section -->
{% include 'produits/partials/footer.html.twig' %}


{% endblock %}